Repository gepittes/doafacil, pull requests merged in 2019-08, with the labels that each got.

#12 [UPDATE] Atualizando View de Login e Cadastro com Tema DoaFacil e Componente Mascote
  webapp/src/App.vue
  webapp/src/assets/css/styles-doafacil.css
  webapp/src/components/genericos/MascoteGif.vue
  webapp/src/modules/conta/Cadastrar.vue
  webapp/src/modules/conta/Login.vue
  webapp/src/modules/home/FachadaHome.vue
  webapp/src/modules/home/InfoCompany.vue
  webapp/src/router.js
  webapp/src/views/Sobre.vue
  webapp/src/views/home/Home.vue
Labels: update

#14 [FIX] Correções de Layput home Vuetify 2.0.4
  webapp/public/index.html
  webapp/src/App.vue
  webapp/src/assets/bell_notification.gif
  webapp/src/assets/css/styles-doafacil.css
  webapp/src/components/home/BackTop.vue
  webapp/src/components/home/FachadaHome.vue
  webapp/src/components/home/GenericComp.vue
  webapp/src/components/home/InfoCompany.vue
  webapp/src/components/home/InformacoesCards.vue
  webapp/src/components/home/NewsLetter.vue
  webapp/src/components/home/RedesSociais.vue
  webapp/src/main.js
  webapp/src/modules/conta/Cadastrar.vue
  webapp/src/modules/core/Footer.vue
  webapp/src/modules/home/NewsLetter.vue
  webapp/src/plugins/fontawesome.js
  webapp/src/plugins/vuetify.js
  webapp/src/views/home/Home.vue
Labels: fix

#23 Correções de layout e login [FIX | UPDATE]
  api/app/Models/Instituicao.php
  api/database/migrations/2019_07_07_135321_create_instituicao_table.php
  webapp/package.json
  webapp/src/components/home/FachadaHome.vue
  webapp/src/components/instituicao/Instituicao.vue
  webapp/src/components/instituicao/InstituicaoFormulario.vue
  webapp/src/components/instituicao/Instituicoes.vue
  webapp/src/modules/account/actions.js
  webapp/src/modules/alert/Alerta.vue
  webapp/src/modules/core/NaoEncontrado.vue
Labels: add, fix, update

#26 Adicionado diversos recursos e componentes
  api/app/Http/Controllers/InstituicaoController.php
  api/app/Models/Instituicao.php
  api/routes/web.php
  webapp/src/App.vue
  webapp/src/assets/css/styles-doafacil.css
  webapp/src/components/doacao/PontoDoacao.vue
  webapp/src/components/instituicao/Instituicao.vue
  webapp/src/components/instituicao/InstituicaoFormulario.vue
  webapp/src/components/instituicao/Instituicoes.vue
  webapp/src/components/instituicao/Perfil.vue
  webapp/src/modules/account/actions.js
  webapp/src/modules/conta/Login.vue
  webapp/src/modules/conta/MeuCadastro.vue
  webapp/src/modules/conta/actions.js
  webapp/src/modules/core/AppBar.vue
  webapp/src/modules/core/BarraLateral.vue
  webapp/src/modules/core/Configuracao.vue
  webapp/src/modules/core/MenuInstituicao.vue
  webapp/src/modules/instituicao/actions.js
  webapp/src/modules/instituicao/getters.js
  webapp/src/modules/instituicao/mutations.js
  webapp/src/modules/instituicao/state.js
  webapp/src/router.js
  webapp/src/views/Main.vue
Labels: add, fix, update

#27 [REVERT] Desfazendo alterações de estrutura do layout
  webapp/src/assets/css/styles-doafacil.css
  webapp/src/components/doacao/PontoDoacao.vue
  webapp/src/components/instituicao/Instituicoes.vue
  webapp/src/modules/account/actions.js
  webapp/src/modules/core/AppBar.vue
  webapp/src/modules/core/BarraLateral.vue
  webapp/src/modules/core/Configuracao.vue
  webapp/src/router.js
  webapp/src/views/Main.vue
Labels: fix

#31 [UPDATE] Atualizando de app bar, responsividade system grid 2.0.x Vuetify
  webapp/public/index.html
  webapp/src/App.vue
  webapp/src/components/home/FachadaHome.vue
  webapp/src/components/home/GenericComp.vue
  webapp/src/components/home/InfoCompany.vue
  webapp/src/modules/core/AppBar.vue
  webapp/src/views/home/Home.vue
Labels: fix, update
