Repository gepittes/doafacil, pull requests merged in 2019-09, with the labels that each got.

#32 [FIX | UPDATE] Adicionando menu lateral com tratativas de responsividade
  webapp/src/components/home/FachadaHome.vue
  webapp/src/components/home/InformacoesCards.vue
  webapp/src/components/home/NewsLetter.vue
  webapp/src/components/home/RedesSociais.vue
  webapp/src/components/instituicao/Instituicao.vue
  webapp/src/components/instituicao/Perfil.vue
  webapp/src/modules/conta/Cadastrar.vue
  webapp/src/modules/conta/Login.vue
  webapp/src/modules/core/AppBar.vue
  webapp/src/modules/core/BarraLateral.vue
  webapp/src/router.js
  webapp/src/views/Instituicao/Instituicoes.vue
  webapp/src/views/Instituicao/Perfil.vue
Labels: fix, update

#33 [FIX] Listando instituições somente do user referente logado e função de atualização.
  api/app/Http/Controllers/InstituicaoController.php
  api/app/Models/Instituicao.php
  api/database/migrations/2019_07_07_135321_create_instituicao_table.php
  api/routes/web.php
  webapp/src/components/instituicao/Instituicao.vue
  webapp/src/components/instituicao/InstituicaoFormulario.vue
  webapp/src/modules/core/AppBar.vue
  webapp/src/modules/instituicao/actions.js
  webapp/src/modules/instituicao/getters.js
  webapp/src/modules/instituicao/mutations.js
  webapp/src/modules/instituicao/state.js
  webapp/src/modules/instituicao/types.js
  webapp/src/views/Instituicao/Instituicoes.vue
Labels: update

#36 [ADD] Modulo base de Evento (Layout e Vuex Cycle)
  webapp/src/components/evento/Calendario.vue
  webapp/src/components/evento/EventoCard.vue
  webapp/src/components/evento/EventoFormulario.vue
  webapp/src/modules/core/BarraLateral.vue
  webapp/src/modules/evento/actions.js
  webapp/src/modules/evento/getters.js
  webapp/src/modules/evento/index.js
  webapp/src/modules/evento/mutations.js
  webapp/src/modules/evento/state.js
  webapp/src/modules/evento/types.js
  webapp/src/router.js
  webapp/src/store.js
  webapp/src/views/evento/Eventos.vue
Labels: add, feature

#41 [FIX] Corrigir erro quando exercuta a migrate:fresh Closes #40
  api/.env.example
Labels: fix

#42 ADD e READ do Modulo de Eventos
  api/app/Http/Controllers/Evento/EventoController.php
  api/app/Models/Evento.php
  api/database/migrations/2019_09_12_121739_create_eventos_table.php
  api/routes/web.php
  webapp/src/components/evento/EventoCard.vue
  webapp/src/components/evento/EventoFormulario.vue
  webapp/src/modules/evento/actions.js
  webapp/src/modules/evento/getters.js
  webapp/src/modules/evento/mutations.js
  webapp/src/modules/evento/state.js
  webapp/src/modules/evento/types.js
  webapp/src/views/evento/Eventos.vue
Labels: add

#44 CRUD Pontos de doacao Closes #34
  api/app/Http/Controllers/Ponto/PontoController.php
  api/app/Http/Controllers/PontoDeDoacaoController.php
  api/app/Models/PontoDeDoacao.php
  api/app/Services/Ponto/PontoServices.php
  api/database/migrations/2019_09_04_135556_create_ponto_de_doacaos_table.php
  api/routes/web.php
  webapp/src/components/ponto/Ponto.vue
  webapp/src/components/ponto/PontoCard.vue
  webapp/src/components/ponto/PontoFormulario.vue
  webapp/src/modules/ponto/actions.js
  webapp/src/modules/ponto/getters.js
  webapp/src/modules/ponto/mutations.js
  webapp/src/modules/ponto/state.js
  webapp/src/modules/ponto/types.js
  webapp/src/views/ponto/Pontos.vue
Labels: add, feature, update

#45 CRUD - Evento - DELETE, LIST e UX/UI
  api/app/Http/Controllers/Evento/EventoController.php
  webapp/src/components/evento/EventoCard.vue
  webapp/src/components/evento/EventoFormulario.vue
  webapp/src/filters.js
  webapp/src/modules/evento/actions.js
  webapp/src/modules/evento/getters.js
  webapp/src/modules/evento/mutations.js
  webapp/src/modules/evento/state.js
  webapp/src/modules/evento/types.js
  webapp/src/views/evento/Eventos.vue
Labels: add, feature

#47 [ADD | UPDATE] Função de update em eventos e correções de layout DEFAULT e layout formulário
  api/app/Http/Controllers/Evento/EventoController.php
  api/app/Models/Evento.php
  webapp/src/components/evento/EventoCard.vue
  webapp/src/components/evento/EventoFormulario.vue
  webapp/src/modules/core/AppBar.vue
  webapp/src/modules/core/BarraLateral.vue
  webapp/src/modules/evento/actions.js
  webapp/src/modules/evento/getters.js
  webapp/src/modules/evento/mutations.js
  webapp/src/modules/evento/state.js
  webapp/src/modules/evento/types.js
  webapp/src/views/evento/Eventos.vue
  webapp/src/views/layouts/Default.vue
Labels: add, update

#46 [REFACTOR] controller router module e model e add instituicaoServices by instituicao
  api/app/Http/Controllers/Instituicao/InstituicaoController.php
  api/app/Http/Controllers/InstituicaoController.php
  api/app/Models/Instituicao.php
  api/app/Services/Instituicao/InstituicaoServices.php
  api/routes/web.php
  webapp/src/modules/instituicao/actions.js
  webapp/src/modules/instituicao/getters.js
  webapp/src/modules/instituicao/mutations.js
  webapp/src/modules/ponto/actions.js
Labels: update

#49 [UPDATE] Atualiza componente Atualizar Minha Conta Closes #48
  api/app/Http/Controllers/Conta/ContaController.php
  api/app/Http/Middleware/JWTMiddleware.php
  api/app/Http/Middleware/JsonResponseStyle.php
  api/app/Services/Conta.php
  api/routes/web.php
  webapp/src/modules/account/actions.js
  webapp/src/modules/account/getters.js
  webapp/src/modules/account/mutations.js
  webapp/src/modules/account/state.js
  webapp/src/modules/account/types.js
  webapp/src/modules/conta/MeuCadastro.vue
  webapp/src/modules/conta/actions.js
  webapp/src/modules/conta/getters.js
  webapp/src/modules/conta/mutations.js
  webapp/src/modules/conta/state.js
  webapp/src/modules/core/AppBar.vue
  webapp/src/modules/core/Configuracao.vue
  webapp/src/modules/core/MenuInstituicao.vue
Labels: add, feature

#52 [ADD] Correções de Responsividade, Calendário de Eventos, delete de Instituição somente por Configurações da Conta
  webapp/src/components/evento/Calendario.vue
  webapp/src/components/instituicao/Instituicao.vue
  webapp/src/modules/core/Configuracao.vue
  webapp/src/views/evento/Eventos.vue
  webapp/src/views/ponto/Pontos.vue
Labels: add, fix, update

#53 [UPDATE] Listagem de Eventos e Pontos no Perfil de Instituição
  webapp/src/components/evento/EventoCard.vue
  webapp/src/components/ponto/PontoCard.vue
  webapp/src/router.js
  webapp/src/views/Instituicao/Perfil.vue
  webapp/src/views/ponto/Pontos.vue
Labels: add, update
